### ISSUE TITLE
Bugs reported

### ISSUE THREAD

**Issue by ph2708** [netpanzer/netpanzer#18]
Release 0.9.0-RC-5

Operational System: Windows 10 Pro

1º When changing the resolution, the mouse sometimes no longer moves, having to close the game and open it again.

2º In the chat, the alignment of the player's flag and the text are not aligned.

3º Blurry letters.

<img width="959" alt="Screenshot_1" src="https://github.com/netpanzer/netpanzer/assets/56886364/6c1967b9-1c55-43a7-a156-424eb3c1a3d7">
<img width="403" alt="Screenshot_2" src="https://github.com/netpanzer/netpanzer/assets/56886364/77de27cc-5814-4763-9ed2-46417d1490e7">
<img width="101" alt="Screenshot_3" src="https://github.com/netpanzer/netpanzer/assets/56886364/82882520-04c8-4858-b94f-cc0385a25edc">

**Comment by winrid** [comment]
Thanks! In the future please create separate issues for each bug.

#3 is tricky. It's just resolution scaling. You can make it more clear by making the resolution match your desktop resolution when full screen. We may revert the scaling if people don't like it.

**Comment by winrid** [comment]
#2 fixed in https://github.com/netpanzer/netpanzer/pull/20

**Comment by winrid** [comment]
#1 fixed in https://github.com/netpanzer/netpanzer/pull/22

**Comment by winrid** [comment]
#3 fixed in https://github.com/netpanzer/netpanzer/pull/21
