### ISSUE TITLE
On Windows, meson setup fails to find libintl.h

### ISSUE THREAD

**Issue by winrid** [netpanzer/netpanzer#185]
```
po\meson.build:23:20: ERROR: C header 'libintl.h' not found
```

I get this on setting up build dir.

**Comment by andy5995** [comment]
add '-Dnls=false' to the setup options.

**Comment by winrid** [comment]
Thanks, that seems to work. Should I commit that?

**Comment by andy5995** [comment]
Let's disable it for Windows from the meson.build for now. Soon I'll add this wrap https://github.com/frida/proxy-libintl

**Comment by andy5995** [comment]
> Let's disable it for Windows from the meson.build for now.

I'll do that shortly, unless you want to take a crack at it.

**Comment by winrid** [comment]
I'll let you mess with the meson stuff for now :)

**Comment by andy5995** [comment]
> I'll let you mess with the meson stuff for now :)

I got it. Could you take of these two files when you have time? https://github.com/netpanzer/netpanzer/pull/169#issuecomment-1911650198

**Comment by winrid** [comment]
sure thing - created issue so I don't forget: https://github.com/netpanzer/netpanzer/issues/189

**Comment by andy5995** [comment]
> Let's disable it for Windows from the meson.build for now. Soon I'll add this wrap https://github.com/frida/proxy-libintl

Now that #183 is merged, I'll start on this next.

**Comment by winrid** [comment]
Nice!
