### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by winrid** [netpanzer/netpanzer#186]
Seem to get this randomly w/ sanitizer on:

```
/usr/include/c++/11/bits/stl_vector.h:1046:34: runtime error: reference binding to null pointer of type 'struct value_type'
../src/NetPanzer/Particles/ParticleInterface.cpp:981:74: runtime error: member access within null pointer of type 'struct value_type'
```

**Comment by andy5995** [comment]
Completed in https://github.com/netpanzer/netpanzer/pull/187

**Comment by winrid** [comment]
Oh forgot to close, thanks. Was thinking it would close based on branch name, but I have to type "fixes #N" in the description... which I usually do .. :)

**Comment by andy5995** [comment]
No problem, don't  worry about it. Things like that are gonna happen to both of us. ;)
