### ISSUE TITLE
Design system to lookup strings

### ISSUE THREAD

**Issue by andy5995** [netpanzer/netpanzer#217]
There needs to be a system where strings can be looked up from a single source.

The help strings are duplicated in HelpScrollView.cpp and HelpScrollViewAlt.cpp

There are at least six occurrences of the string "Exit netPanzer" throughout the code.

To mark a string for translation, it has to be wrapped in '_(' and ')'. Doing that for duplicate strings is unnecessary maintenance. Also... it's just bad practice to have so many duplicate strings.

This blocks #193 unfortunately.

**Comment by winrid** [comment]
Just to clarify, we shouldn't store *all* strings in one place.

The duplicate strings you mention should just be refactored.

**Comment by winrid** [comment]
I'm going to close this. I *really* do not want every game string in one place.

Just refactor the help screen stuff. The exit netpanzer string can be stored in a global somewhere, or just deal with the duplicates, not a big deal. Sometimes duplication is better.
