### ISSUE TITLE
Clang build failing when C++ flag is used to compile C

### ISSUE THREAD

**Issue by andy5995** [netpanzer/netpanzer#45]
Note the clang build fails at https://github.com/netpanzer/netpanzer/actions/runs/7390619698/job/20105882173#step:6:2657

```
clang -o build/release/src/Lib/lua/lopcodes.o -c -DPACKAGE_VERSION=\"0.9.0-RC6\" -std=c++17 -O2 -s -Wall -Isrc/Lib/lua src/Lib/lua/lopcodes.c
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
error: invalid argument '-std=c++17' not allowed with 'C'
scons: *** [build/release/src/Lib/lua/lopcodes.o] Error 1
```

**Comment by winrid** [comment]
@andy5995 did you plan on taking a look at this? if not I will in the next couple weeks when I get time. I think the sconstruct script just needs some love.

**Comment by andy5995** [comment]
No, my only experience with scons is the 2 lines I added yesterday and I'm mostly only interested in @mesonbuild these days. I've switched all my projects to meson in fact. Are you attached to the scons build system? Any interest in changing to meson at some point?

**Comment by winrid** [comment]
My experience with scons is the last 8 months of working on netpanzer :) I am not attached to it. One of my goals is to compile NetPanzer to WASM so people can play in the browser, as long as meson doesn't block that I am happy. I had trouble with that with Scons, so far.

The feedback I read on Meson seems fairly mixed, but happy to try it. I also found [xmake](https://github.com/xmake-io/xmake) which looks promising?

**Comment by andy5995** [comment]
Looks like meson supports cross-compiling with emscripten to create wasm files https://mesonbuild.com/Release-notes-for-0-52-0.html#experimental-webassembly-support-via-emscripten

**Comment by winrid** [comment]
Nice! Feel free to create a PR to see how it would look.

I have fixed the issue mentioned here, build now passing.

**Comment by andy5995** [comment]
Ok. Good work!
