### ISSUE TITLE
Menu freezes in some cases when in full-screen at options menu

### ISSUE THREAD

**Issue by andy5995** [netpanzer/netpanzer#73]
Version: c54b039
OS: Manjaro

The mouse left trails, and clicking on "Exit" did nothing. Alt-Enter does nothing. I can get back to my desktop with Alt-tab.

I don't know how to reproduce this yet.

![image](https://github.com/netpanzer/netpanzer/assets/16764864/a4f5fcb0-a9d6-479f-bb21-6b2e43a3f79c)

**Comment by winrid** [comment]
Was this after changing the screen resolution by chance?

**Comment by andy5995** [comment]
Yes.

**Comment by winrid** [comment]
The issue then is most likely in here: https://github.com/netpanzer/netpanzer/blob/master/src/NetPanzer/System/SDLVideo.cpp#L82

**Comment by winrid** [comment]
did not test yet but I think this can be caused if we throw an exception in this method, it would be nice if we could somehow just surface the error to the user instead of crashing or partially crashing

**Comment by winrid** [comment]
Yes, that would be a good first step!

**Comment by winrid** [comment]
@andy5995 should be good now. please reopen if you run into this again
