### ISSUE TITLE
Config file doesn't get created anymore

### ISSUE THREAD

**Issue by andy5995** [netpanzer/netpanzer#84]
The game doesn't create a config file anymore. I removed my old '~/.netpanzer' directory a few days ago, and notice there's now nothing in the ~/.netpanzer/config directory (which did get created automatically), even though I've run the game several times.

**Comment by winrid** [comment]
Did the game exit successfully? Maybe caused by changes to fix #26

**Comment by andy5995** [comment]
Yes, exited successfully.

**Comment by winrid** [comment]
hah, oops!
