### ISSUE TITLE
Change main menu

### ISSUE THREAD

**Issue by andy5995** [netpanzer/netpanzer#97]
### Discussed in https://github.com/netpanzer/netpanzer/discussions/96

<div type='discussions-op-text'>

<sup>Originally posted by **andy5995** January 10, 2024</sup>
I'm not fond of this bright red screen.  Are there plans for this screen? Like an image? Or can we reduce the brightness of that REDness?

![image](https://github.com/netpanzer/netpanzer/assets/16764864/6f9ea7ab-34bf-4c1f-9d04-c35a28ef95a7)
</div>

**Comment by andy5995** [comment]
The red and white labels I have a problem with as well. What other colors would work there?

bright green or yellow foreground on black background?

**Comment by andy5995** [comment]
Hmmm... after I pulled, my screen doesn't match up with yours...

![image](https://github.com/netpanzer/netpanzer/assets/16764864/d62fb44b-b828-4dda-8547-144e4fe20eaf)

**Comment by winrid** [comment]
Have to recompile too

**Comment by andy5995** [comment]
Ah, I forgot to copy '_build/netpanzer' after the build.

Works... Also tested the appimage.
