### ISSUE TITLE
Remove a few lines from the credits screen and fix URL

### ISSUE THREAD

**Issue by andy5995** [netpanzer/netpanzer#99]
Ok if I do some work on the Credits screen?

https://github.com/netpanzer/netpanzer/blob/eadcbc5b1fad0084c26a1c77eace8828283b9bab/src/NetPanzer/Views/MainMenu/CreditsScrollView.cpp#L40-L60

The URL is still SourceForge.

I'd like to remove the description and version because it seems like it's not necessary (goal is to reduce code maintenance). I feel that if someone is looking at the credits screen, they've already read the game description somewhere else.

As for the URL, should I make a Package::GetUrl function?

**Comment by winrid** [comment]
> The URL is still SourceForge.
oops!

> As for the URL, should I make a Package::GetUrl function?
not a bad idea!

you should also add your name in here in credits, I had planned to do that. I also plan to add a thank you to Fu.

**Comment by andy5995** [comment]
What do you think about removing both URLs there completely, and adding one to the '--help' output?

**Comment by winrid** [comment]
Let's keep the URL and point to github, it probably does more good than harm. The website - point to netpanzer.io
